/**
 * spaceAssets.ts - Centralized 3D Asset Manifest & Licensing Ledger for Babylon.js Cosmos
 * 
 * Every external asset is registered with its category, model path, default scale factor,
 * rotation offset, and attribution licensing metadata.
 */

export interface SpaceAssetItem {
  id: string;
  name: string;
  category: 'planet' | 'asteroid' | 'station' | 'ship' | 'satellite' | 'debris' | 'special';
  model: string;
  fallbackType?: string;
  source: 'Sketchfab' | 'Procedural PBR';
  modelUid?: string;
  creator?: string;
  creatorUrl?: string;
  license: string;
  sourceUrl?: string;
  defaultScale: number;
  rotationOffset?: { x: number; y: number; z: number };
  attributionNotes?: string;
}

export const SPACE_ASSETS: Record<string, SpaceAssetItem> = {
  // ==========================================
  // 1. STARFIGHTERS & SPACECRAFT
  // ==========================================
  'ship-player-light-fighter': {
    id: 'ship-player-light-fighter',
    name: 'Light Fighter Spaceship',
    category: 'ship',
    model: '/assets/space/ships/player/light_fighter.glb',
    fallbackType: 'procedural-pbr-fighter',
    source: 'Sketchfab',
    modelUid: '51616ef53af84fe595c5603cd3e0f3e1',
    creator: 'Kerem Kavalci (@Keremz)',
    creatorUrl: 'https://sketchfab.com/Keremz',
    license: 'Sketchfab Free Standard License',
    sourceUrl: 'https://sketchfab.com/3d-models/light-fighter-spaceship-free-51616ef53af84fe595c5603cd3e0f3e1',
    defaultScale: 0.445,
    rotationOffset: { x: 0, y: Math.PI, z: 0 },
    attributionNotes: 'Concept by Tobias Frank (EVERSPACE). Derivative 3D starfighter mesh.',
  },
  'ship-npc-spaceship': {
    id: 'ship-npc-spaceship',
    name: 'Spaceship Free 001',
    category: 'ship',
    model: '/assets/space/ships/npc/spaceship.glb',
    fallbackType: 'procedural-scout',
    source: 'Sketchfab',
    modelUid: '9a81a5167c474530881e55127e275c6c',
    creator: 'ritordp',
    creatorUrl: 'https://sketchfab.com/ritordp',
    license: 'CC Attribution',
    sourceUrl: 'https://sketchfab.com/3d-models/spaceship-free-001-9a81a5167c474530881e55127e275c6c',
    defaultScale: 1.6,
    rotationOffset: { x: 0, y: Math.PI, z: 0 },
  },
  'ship-npc-freighter': {
    id: 'ship-npc-freighter',
    name: 'Atlas Heavy Cargo Freighter',
    category: 'ship',
    model: '/assets/space/ships/npc/freighter.glb',
    fallbackType: 'procedural-freighter',
    source: 'Procedural PBR',
    license: 'MIT / Commercial Permitted',
    defaultScale: 1.8,
    rotationOffset: { x: 0, y: 0, z: 0 },
  },
  'ship-npc-scout': {
    id: 'ship-npc-scout',
    name: 'Valkyrie Recon Scout',
    category: 'ship',
    model: '/assets/space/ships/npc/scout.glb',
    fallbackType: 'procedural-scout',
    source: 'Procedural PBR',
    license: 'MIT / Commercial Permitted',
    defaultScale: 0.38,
    rotationOffset: { x: 0, y: 0, z: 0 },
  },
  'ship-npc-miner': {
    id: 'ship-npc-miner',
    name: 'Goliath Asteroid Harvester',
    category: 'ship',
    model: '/assets/space/ships/npc/miner.glb',
    fallbackType: 'procedural-miner',
    source: 'Procedural PBR',
    license: 'MIT / Commercial Permitted',
    defaultScale: 1.2,
    rotationOffset: { x: 0, y: 0, z: 0 },
  },

  // ==========================================
  // 2. CELESTIAL BODIES (SUN & MERCURY -> PLUTO + MOON)
  // ==========================================
  'star-sun': {
    id: 'star-sun',
    name: 'The Sun (Sol)',
    category: 'planet',
    model: '/assets/space/planets/sun/model.glb',
    fallbackType: 'pbr-sun-core',
    source: 'Sketchfab',
    modelUid: 'af2874610d5e4cbdbf49bc951b500bda',
    creator: 'Cybertron B-127 (@robo-reboot)',
    creatorUrl: 'https://sketchfab.com/robo-reboot',
    license: 'CC Attribution',
    sourceUrl: 'https://sketchfab.com/3d-models/sun-af2874610d5e4cbdbf49bc951b500bda',
    defaultScale: 10.4,
  },
  'planet-mercury': {
    id: 'planet-mercury',
    name: 'Mercury',
    category: 'planet',
    model: '/assets/space/planets/mercury/model.glb',
    fallbackType: 'pbr-crater-planet',
    source: 'Procedural PBR',
    modelUid: 'cfbcea0971c64c3d8dbfa0de2dc9f320',
    license: 'NASA / Public Domain / PBR',
    defaultScale: 2.2,
  },
  'planet-venus': {
    id: 'planet-venus',
    name: 'Venus',
    category: 'planet',
    model: '/assets/space/planets/venus/model.glb',
    fallbackType: 'pbr-cloud-planet',
    source: 'Sketchfab',
    modelUid: 'd497ce25553447f3b7b679110c85cfa1',
    creator: 'Akshat (@shooter24994)',
    creatorUrl: 'https://sketchfab.com/shooter24994',
    license: 'CC Attribution',
    sourceUrl: 'https://sketchfab.com/3d-models/venus-d497ce25553447f3b7b679110c85cfa1',
    defaultScale: 2.8,
  },
  'planet-earth': {
    id: 'planet-earth',
    name: 'Earth',
    category: 'planet',
    model: '/assets/space/planets/earth/model.glb',
    fallbackType: 'pbr-earth-multisphere',
    source: 'Sketchfab',
    modelUid: '072ccdc6820c4cb698349d9b71089269',
    creator: 'PixelMotion4096',
    creatorUrl: 'https://sketchfab.com/pixelmotion4096',
    license: 'CC Attribution',
    sourceUrl: 'https://sketchfab.com/3d-models/realistic-earth-planet-072ccdc6820c4cb698349d9b71089269',
    defaultScale: 3.0,
  },
  'planet-moon': {
    id: 'planet-moon',
    name: 'The Moon (Luna)',
    category: 'planet',
    model: '/assets/space/planets/moon/model.glb',
    fallbackType: 'pbr-moon-sphere',
    source: 'Sketchfab',
    modelUid: '26cc0b7878bb4d919b68e2be399db466',
    creator: 'RenderX',
    creatorUrl: 'https://sketchfab.com/RenderX',
    license: 'CC Attribution',
    sourceUrl: 'https://sketchfab.com/3d-models/moon-26cc0b7878bb4d919b68e2be399db466',
    defaultScale: 0.84,
  },
  'planet-mars': {
    id: 'planet-mars',
    name: 'Mars',
    category: 'planet',
    model: '/assets/space/planets/mars/model.glb',
    fallbackType: 'pbr-mars-sphere',
    source: 'Sketchfab',
    modelUid: 'f98432cf20aa426fb3bd299f699ffd51',
    creator: 'Danny.Gallegos',
    creatorUrl: 'https://sketchfab.com/Danny.Gallegos',
    license: 'CC Attribution',
    sourceUrl: 'https://sketchfab.com/3d-models/mars-f98432cf20aa426fb3bd299f699ffd51',
    defaultScale: 2.5,
  },
  'planet-jupiter': {
    id: 'planet-jupiter',
    name: 'Jupiter',
    category: 'planet',
    model: '/assets/space/planets/jupiter/model.glb',
    fallbackType: 'pbr-gas-giant',
    source: 'Procedural PBR',
    modelUid: 'b23739bf6154492eb30fcd2e758dff08',
    license: 'NASA / Public Domain / PBR',
    defaultScale: 5.6,
  },
  'planet-saturn': {
    id: 'planet-saturn',
    name: 'Saturn',
    category: 'planet',
    model: '/assets/space/planets/saturn/model.glb',
    fallbackType: 'pbr-saturn-rings',
    source: 'Sketchfab',
    modelUid: '9a279abdabc740419474d2b03dbadb59',
    creator: 'jaxtynvalentine46',
    creatorUrl: 'https://sketchfab.com/jaxtynvalentine46',
    license: 'CC Attribution',
    sourceUrl: 'https://sketchfab.com/3d-models/saturn-9a279abdabc740419474d2b03dbadb59',
    defaultScale: 4.6,
  },
  'planet-uranus': {
    id: 'planet-uranus',
    name: 'Uranus',
    category: 'planet',
    model: '/assets/space/planets/uranus/model.glb',
    fallbackType: 'pbr-ice-giant',
    source: 'Sketchfab',
    modelUid: '0009a69dbace44608c0bd09af9ba20db',
    creator: 'Nestaeric',
    creatorUrl: 'https://sketchfab.com/Nestaeric',
    license: 'CC Attribution',
    sourceUrl: 'https://sketchfab.com/3d-models/uranus-0009a69dbace44608c0bd09af9ba20db',
    defaultScale: 3.6,
  },
  'planet-neptune': {
    id: 'planet-neptune',
    name: 'Neptune',
    category: 'planet',
    model: '/assets/space/planets/neptune/model.glb',
    fallbackType: 'pbr-azure-storm',
    source: 'Sketchfab',
    modelUid: '7e7632f6e16b4aaaa7597b9ff91b47b2',
    creator: 'Yanez Designs',
    creatorUrl: 'https://sketchfab.com/Yanez-Designs',
    license: 'CC Attribution',
    sourceUrl: 'https://sketchfab.com/3d-models/neptune-7e7632f6e16b4aaaa7597b9ff91b47b2',
    defaultScale: 3.5,
  },
  'planet-pluto': {
    id: 'planet-pluto',
    name: 'Pluto (Kuiper Dwarf)',
    category: 'planet',
    model: '/assets/space/planets/pluto/model.glb',
    fallbackType: 'pbr-kuiper-dwarf',
    source: 'Sketchfab',
    modelUid: '82bec3a4536c4a608c3b6e219b16a824',
    creator: 'Yanez Designs',
    creatorUrl: 'https://sketchfab.com/Yanez-Designs',
    license: 'CC Attribution',
    sourceUrl: 'https://sketchfab.com/3d-models/pluto-82bec3a4536c4a608c3b6e219b16a824',
    defaultScale: 1.3,
  },

  // ==========================================
  // 3. SPACE STATIONS & OUTPOSTS
  // ==========================================
  'station-01': {
    id: 'station-01',
    name: 'Space Station Prime Citadel',
    category: 'station',
    model: '/assets/space/stations/station_01/model.glb',
    fallbackType: 'procedural-citadel-torus',
    source: 'Sketchfab',
    modelUid: '0da4a24e7edd49159737675ffcc06228',
    creator: 're1monsen',
    creatorUrl: 'https://sketchfab.com/re1monsen',
    license: 'CC Attribution',
    sourceUrl: 'https://sketchfab.com/3d-models/space-station-0da4a24e7edd49159737675ffcc06228',
    defaultScale: 6.5,
  },
  'station-03': {
    id: 'station-03',
    name: 'Space Station 3 Defense Relay',
    category: 'station',
    model: '/assets/space/stations/station_03/model.glb',
    fallbackType: 'procedural-sensor-relay',
    source: 'Sketchfab',
    modelUid: 'a7a6ad10261149cab31aa394bfcf8940',
    creator: 're1monsen',
    creatorUrl: 'https://sketchfab.com/re1monsen',
    license: 'CC Attribution',
    sourceUrl: 'https://sketchfab.com/3d-models/space-station-3-a7a6ad10261149cab31aa394bfcf8940',
    defaultScale: 6.0,
  },
  'station-modules': {
    id: 'station-modules',
    name: 'Space Station Modular Complex',
    category: 'station',
    model: '/assets/space/stations/modules/model.glb',
    fallbackType: 'procedural-mining-rig',
    source: 'Sketchfab',
    modelUid: 'e3ba39a1c78540448542cf937b11feab',
    creator: 're1monsen',
    creatorUrl: 'https://sketchfab.com/re1monsen',
    license: 'CC Attribution',
    sourceUrl: 'https://sketchfab.com/3d-models/space-station-modules-e3ba39a1c78540448542cf937b11feab',
    defaultScale: 5.5,
  },

  // ==========================================
  // 4. ASTEROIDS & CELESTIAL DEBRIS
  // ==========================================
  'asteroid-low-poly': {
    id: 'asteroid-low-poly',
    name: 'Asteroid Field Low-Poly Collection',
    category: 'asteroid',
    model: '/assets/space/asteroids/low_poly/model.glb',
    fallbackType: 'procedural-pbr-rock',
    source: 'Sketchfab',
    modelUid: '24572b5eec404dd7888a76098054cd7a',
    creator: 'Sereib',
    creatorUrl: 'https://sketchfab.com/Sereib',
    license: 'CC Attribution',
    sourceUrl: 'https://sketchfab.com/3d-models/asteroid-field-100-x-low-poly-24572b5eec404dd7888a76098054cd7a',
    defaultScale: 2.2,
  },
  'asteroid-med-poly': {
    id: 'asteroid-med-poly',
    name: 'Asteroid Field Medium-Poly Collection',
    category: 'asteroid',
    model: '/assets/space/asteroids/medium_poly/model.glb',
    fallbackType: 'procedural-pbr-rock',
    source: 'Sketchfab',
    modelUid: '2dc6d949b60a4128a86d5c34f53b136c',
    creator: 'Sereib',
    creatorUrl: 'https://sketchfab.com/Sereib',
    license: 'CC Attribution',
    sourceUrl: 'https://sketchfab.com/3d-models/asteroid-field-100-x-medium-poly-2dc6d949b60a4128a86d5c34f53b136c',
    defaultScale: 2.6,
  },

  // ==========================================
  // 5. SPECIAL CELESTIAL OBJECTS & METEORS
  // ==========================================
  'special-meteorite': {
    id: 'special-meteorite',
    name: 'Deep-Space Ancient Meteorite',
    category: 'special',
    model: '/assets/space/special/meteorite/model.glb',
    fallbackType: 'procedural-void-singularity',
    source: 'Sketchfab',
    modelUid: '0a503e5bec784cbc9082e2f6b2d9f701',
    creator: 'hailphilly',
    creatorUrl: 'https://sketchfab.com/hailphilly',
    license: 'CC Attribution',
    sourceUrl: 'https://sketchfab.com/3d-models/meteorite-0a503e5bec784cbc9082e2f6b2d9f701',
    defaultScale: 2.2,
  },
  'special-meteor': {
    id: 'special-meteor',
    name: 'Hypervelocity Glowing Meteor',
    category: 'special',
    model: '/assets/space/special/meteor/model.glb',
    fallbackType: 'procedural-void-singularity',
    source: 'Sketchfab',
    modelUid: 'd3a5a7e9a7d24b76841bf0f49d56a5f3',
    creator: 'mvrc.art',
    creatorUrl: 'https://sketchfab.com/mvrc.art',
    license: 'CC Attribution',
    sourceUrl: 'https://sketchfab.com/3d-models/meteor-d3a5a7e9a7d24b76841bf0f49d56a5f3',
    defaultScale: 2.5,
  },
};
